name: release

on:
  push:
    branches:
      - main
env:
  GPG_KEY_ID: 65DB550AE78300E6E355194C54B70F4A4F126E06
  GIT_AUTHOR_NAME: boatkit-ci
  GIT_AUTHOR_EMAIL: boatkit@rgst.io
  GIT_COMMITTER_NAME: boatkit-ci
  GIT_COMMITTER_EMAIL: boatkit@rgst.io

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release
