name: tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tool Versions
        uses: jdx/mise-action@v2
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=5m
      - name: lintroller
        run: go run github.com/getoutreach/lintroller/cmd/lintroller@v1.18.8 -config lintroller.yaml ./...

  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tool Versions
        uses: jdx/mise-action@v2
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
        with:
          coverageCommand: make test
          coverageLocations: c.out:gocov
          prefix: github.com/boatkit-io/tugboat
