name: tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
      - name: Lint
        run: mise run lint

  test:
    name: gotestsum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
      - name: Test
        run: mise run test
